### ISSUE TITLE
Mise à jour des données

### ISSUE THREAD

**Issue by dthonon** [oliviergimenez/note-information-nombre-loups#1]
Bonjour,

Est-il possible de disposer de la mise à jour des données et des résultats pour cette année ?

Merci d'avance

**Comment by oliviergimenez** [comment]
Bonjour,
Je pars en mission/vacances, ce sera pour la rentrée ;-)
Olivier

**Comment by dthonon** [comment]
Bonjour,

Sauf erreur, je n'ai pas vu la mise à jour des données et des résultats.

Cordialement
Daniel Thonon

**Comment by oliviergimenez** [comment]
Bonsoir,
Nous prévoyons de faire une publication scientifique en lien avec l'estimation des effectifs, c'est à cette occasion que nous mettrons à disposition les données/analyses mises à jour dans un autre repo. Concernant la note d'information, tout est déjà disponible. 
Cordialement,
Olivier
